[package]
name = "watch-log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.3.17"

[[bin]]
name = "manager"
path = "src/watch-log-manager.rs"

